version: '3.3'
services:
  oasipdb:
    container_name: oasipdb
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=oasip_ssa1_root
      - TZ=Asia/Bangkok
    ports:
      - "3306:3306"
    volumes:
      - ./Database/script/:/docker-entrypoint-initdb.d/

  
  oasipbe:
    container_name: oasipbe
    build: ./oasip-app
    depends_on:
      - oasipdb
    restart: always
    ports:
      - "8080:8080"
    links:
      - oasipdb
  
  oasipfe:
    container_name: oasipfe
    build: ./oasip-front
    depends_on:
      - oasipdb
    restart: always
    links:
      - oasipbe
  
  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/spadmin/certs:/etc/nginx/certs
      - type:bind
        source:/home/spadmin/oasip_ssa1/
        target:/oasipssa1
    links:
      - oasipfe
      - oasipbe


