version: '3.3'
services:
  oasipdb:
    container_name: oasipdb
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./Database/script/empty_data.sql :/docker-entrypoint-initdb.d/

  
  oasipbe:
    container_name: oasipbe
    build: ./oasip-app
    depends_on:
      - oasipdb
    restart: always
    ports:
      - "8080:8080"
    links:
      - oasipdb
  
  oasipfe:
    container_name: oasipfe
    build: ./oasip-front
    depends_on:
      - oasipdb
    restart: always
    volumes: 
      - ./oasip-front/nginxfe.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    links:
      - oasipbe

