version: '3.3'
services:
  oasipdb:
    container_name: oasipdb
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./Database/script/:/docker-entrypoint-initdb.d/

  
  oasipbe:
    container_name: oasipbe
    build: ./oasip-app
    depends_on:
      - oasipdb
    restart: always
    ports:
      - "8080:8080"
    links:
      - oasipdb
  
  oasipfe:
    container_name: oasipfe
    build: ./oasip-front
    depends_on:
      - oasipdb
    restart: always
    ports: 
      - "3000:3000"
    links:
      - oasipbe
  
  nginx_proxy:
    image: nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


