version: '3.8'
services:
  oasipdb:
    container_name: oasipdb
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./database/script/:/docker-entrypoint-initdb.d/

  
  oasipbe:
    container_name: oasipbe
    build: ./oasip-app
    depends_on:
      - oasipdb
    restart: always
    ports:
      - 8080:8080
    links:
      - oasipdb
