-- MySQL Script generated by MySQL Workbench
-- Tue May 10 17:40:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oasip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oasip
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `oasip` ;
USE `oasip` ;

-- -----------------------------------------------------
-- Table `oasip`.`eventCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`eventCategories` (
  `eventCategoryId` INT NOT NULL AUTO_INCREMENT,
  `eventCategoryName` VARCHAR(100) NOT NULL,
  `eventCategoryDescription` VARCHAR(500) NULL DEFAULT NULL,
  `eventDuration` INT NOT NULL,
  `imagePath` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`eventCategoryId`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`status` (
  `statusId` INT NOT NULL AUTO_INCREMENT,
  `statusName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`statusId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`events` (
  `bookingId` INT NOT NULL AUTO_INCREMENT,
  `bookingName` VARCHAR(100) NOT NULL,
  `bookingEmail` VARCHAR(100) NOT NULL,
  `eventDate` DATE NOT NULL,
  `eventStartTime` TIME NOT NULL,
  `eventEndTime` TIME NOT NULL,
  `eventDuration` INT NOT NULL,
  `eventNotes` VARCHAR(500) NULL DEFAULT NULL,
  `eventCategoryId` INT NOT NULL,
  `statusId` INT NOT NULL,
  PRIMARY KEY (`bookingId`),
  INDEX `fk_event_eventCategory_idx` (`eventCategoryId` ASC) VISIBLE,
  INDEX `fk_events_status1_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_event_eventCategory`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `oasip`.`eventCategories` (`eventCategoryId`),
  CONSTRAINT `fk_events_status1`
    FOREIGN KEY (`statusId`)
    REFERENCES `oasip`.`status` (`statusId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
