-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 23:02:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT ;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS ;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION ;
SET NAMES utf8mb4 ;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET GLOBAL time_zone = '+7:00';

-- -----------------------------------------------------
-- Databse oasip
-- -----------------------------------------------------
CREATE database IF NOT EXISTS `oasip` ;
USE `oasip` ;

-- -----------------------------------------------------
-- Table `oasip`.`eventCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`eventCategories` (
  `eventCategoryId` INT NOT NULL AUTO_INCREMENT,
  `eventCategoryName` VARCHAR(100) NOT NULL,
  `eventCategoryDescription` VARCHAR(500) NULL DEFAULT NULL,
  `eventDuration` INT NOT NULL,
  PRIMARY KEY (`eventCategoryId`),
  UNIQUE INDEX `eventCategoryName_UNIQUE` (`eventCategoryName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`roles` (
  `roleId` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(100) NOT NULL,
  `userEmail` VARCHAR(50) NOT NULL,
  `createdOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOn` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `roleId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  UNIQUE INDEX `userEmail_UNIQUE` (`userEmail` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`roleId`)
    REFERENCES `oasip`.`roles` (`roleId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`clinicsRegistration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`clinicsRegistration` (
  `clinicRegistrationId` INT NOT NULL AUTO_INCREMENT,
  `eventCategoryId` INT NOT NULL,
  `userId` INT NOT NULL,
  `eventCategoryName` VARCHAR(100) NOT NULL,
  `userName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`clinicRegistrationId`),
  INDEX `fk_eventCategories_has_user_user1_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_eventCategories_has_user_eventCategories1_idx` (`eventCategoryId` ASC) VISIBLE,
  CONSTRAINT `fk_eventCategories_has_user_eventCategories1`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `oasip`.`eventCategories` (`eventCategoryId`),
  CONSTRAINT `fk_eventCategories_has_user_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `oasip`.`users` (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`status` (
  `statusId` INT NOT NULL AUTO_INCREMENT,
  `statusName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`statusId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `oasip`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oasip`.`events` (
  `bookingId` INT NOT NULL AUTO_INCREMENT,
  `bookingName` VARCHAR(100) NOT NULL,
  `bookingEmail` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `eventStartTime` DATETIME NOT NULL,
  `eventEndTime` DATETIME NOT NULL,
  `eventDuration` INT NOT NULL,
  `eventNotes` VARCHAR(500) NULL DEFAULT NULL,
  `eventCategoryId` INT NOT NULL,
  `statusId` INT NOT NULL,
  PRIMARY KEY (`bookingId`),
  INDEX `fk_event_eventCategory_idx` (`eventCategoryId` ASC) VISIBLE,
  INDEX `fk_events_status1_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_event_eventCategory`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `oasip`.`eventCategories` (`eventCategoryId`),
  CONSTRAINT `fk_events_status1`
    FOREIGN KEY (`statusId`)
    REFERENCES `oasip`.`status` (`statusId`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


--
-- create user
--

create user 'admin'@'%' identified by 'oasip_ssa1_admin';
create user 'dev'@'%' identified by 'oasip_ssa1_dev';
create user 'user'@'%' identified by 'oasip_ssa1_user';
grant all privileges on *.* to 'admin'@'%';
grant select ,insert ,update , delete on oasip.* to 'user'@'%';
grant select ,insert ,update , delete on oasip.* to  'dev'@'%' ;
