# This is a basic workflow to help you get started with Actions

name: build_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['dev']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Shutdown container
        run: |
          docker-compose down
          
      - name: Clear storage
        run: |
          docker-compose rm -vf oasipfe oasipbe oasipdb nginx_proxy
          rm -rf /home/spadmin/uploads/guest || true
          rm -rf /home/spadmin/uploads/user || true
      # Runs a set of commands using the runners shell
      - name: Build deploy
        run: |
          docker-compose up -d --build
          
      - name: Remove used images
        run: |
          docker image prune -af
